# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Serializer
version:      0.29
version_from: lib/Data/Serializer.pm
installdirs:  site
requires:
    Data::Dumper:                  2.08
    Digest::SHA1:                  0
    IO::File:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
