--- #YAML:1.0
name:                Data-Serializer
version:             0.42
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Data::Dumper:                  2.08
    Digest::SHA:                   0
    IO::File:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Neil Neely (neil@neely.cx)
